xacrimon/dashmap

src/iter.rs
src/lib.rs
src/mapref/entry.rs
src/util.rs

Swap over to use `SharedValue` and remove `util::to_mut`

---

src/util.rs

Forgot to add docs in #11, so now for docs!

added docs for `SharedValue`

---

src/lib.rs

As mentioned in issue #26, it would be nice to use the provided HashBuilder for shard selection.
This may have a performance impact?

Use provided HashBuilder for shard selection

---

src/lib.rs

Implement Default for DashMap<K, V, S>.

---

src/hasher.rs
src/iter.rs
src/lib.rs
src/mapref/entry.rs

Fixed #40 without a change in public API (It is backwards-compatible)

Fix double hash issue

---

src/hasher.rs
src/iter.rs
src/lib.rs
src/mapref/entry.rs

Revert "Revert "Fix double hash issue""

---

src/mapref/one.rs

I have need of this feature. :)

Add method to downgrade RefMut to Ref

---

src/lib.rs
src/lock.rs
src/read_only.rs
src/t.rs

This is an implementation of what was discussed in issue https://github.com/xacrimon/dashmap/issues/65.
Feel free to request naming/API changes or more tests/comments.

Implement ReadOnlyView

---

src/iter.rs

While debugging some unrelated code, I noticed the backtrace had a bunch of frames that were all in the `next` implementation of the DashMap iterators - in my particular case, the recursion had resulted in overflowing the stack space I had allocated for a green thread. While that is not likely to happen in "normal" Rust code, it is still unnecessary to use recursion here when a simple loop will suffice, which will avoid the overhead of allocating additional stack frames when the space in a single frame can be reused.
If you had another reason for using recursion here, then feel free to disregard - though it would be helpful to know what I missed for the future.
Thanks for the great library!

Fix unnecessary recursion in iterators

---

src/lib.rs

fix doc typo in lib.rs (alter)

---

src/serde.rs

I made it serialize to a json array (Like std::collections::HashMap)

fix #105 Serde support for DashSet

---

src/mapref/multiple.rs
src/mapref/one.rs
src/setref/multiple.rs
src/setref/one.rs

Specify explicit lifetimes for key/value

---

src/lib.rs
src/t.rs

Add "alter" variation but for immutable borrows

---

src/lib.rs
src/t.rs
src/try_result.rs

Closes #120.
Wasn't quite sure where to put `TryResult`, let me know if there's a better place.

Add DashMap::try_get, DashMap::try_get_mut, DashMap::try_entry

---

src/iter.rs
src/lib.rs
src/mapref/entry.rs
src/mapref/multiple.rs
src/mapref/one.rs
src/rayon/map.rs
src/setref/multiple.rs
src/setref/one.rs

This PR resolves the currently open security advisory against dashmap and thus #167.
Action items
- Get cross-review
- Close #167 
- Update advisory

Resolve reference smuggling SEC fix

---

src/lib.rs

Signed-off-by: Leo Lu <luyuxuanleo@gmail.com>

Add check for if a shard_amount is a power of two.

---

Cargo.toml
README.md
src/iter.rs
src/lib.rs
src/lock.rs
src/mapref/entry.rs
src/mapref/multiple.rs
src/mapref/one.rs
src/rayon/map.rs
src/set.rs
src/setref/one.rs
src/t.rs

Fixes #191 
Fixes #201
Fixes #195 
This introduces breaking changes in how Send/Sync bounds are implemented, this was unfortunately needed to fix unsoundness in the API.

Address major issues

---

Cargo.toml
src/lock.rs
src/table.rs

This PR switches out the sketchy spinlock for a better lock implementation.
Fixes #213 
Fixes #206

Use a proper lock implementation

---

.github/workflows/ci.yml
Cargo.toml
README.md
rust-toolchain
src/iter.rs
src/lib.rs
src/rayon/map.rs
src/set.rs

update deps & toolchain to stable-1.64

---

Cargo.lock
Cargo.toml
README.md
rust-toolchain.toml

Bump msrv to 1.65

---

src/lib.rs

fix deadlock in shrink_to_fit

---

src/lib.rs

We can collect directly into the `Box<[T]>` to avoid pushing to a `Vec`, which could overallocate and require a reallocation when shrinking in `Vec::into_boxed_slice` or have to reallocate multiple times as it wouldn't know the finishing capacity.

Avoid overallocating or growing Vec in Clone
