src/iter.rs, src/lib.rs, src/mapref/entry.rs, src/mapref/multiple.rs, src/mapref/one.rs, src/t.rs
This is my attempt at adding `with_hasher` and `with_capacity_and_hasher` to `DashMap`. 
It unfortunately is rather invasive, as `HashMap<K, V>` needs to be changed to `HashMap<K, V, S>`, and `HashMap` is referenced all over the place. I could probably remove some `BuildHasher` bounds if you think that is cleaner.
Oh and if you want it should be easy to switch to SipHash (#12), but perhaps that should be a major version bump...
=> Allow passing the hasher.

src/lib.rs
Hi! I was adding DashMap to [redis-oxide](https://github.com/dpbriggs/redis-oxide) and unfortunately DashMap was segfaulting during benchmarks.
I looked into it and turns out `Default` was setting `DashMap::ncb` to 0, which later caused an overflowing rightshift in `determine_map`.
This test case fails on the current master:
```rust
#[cfg(test)]
mod tests {
use crate::DashMap;
#[test]
fn test_default() {
let dm: DashMap<u32, u32> = DashMap::default();
dm.insert(0, 0);
assert_eq!(dm.get(&0).unwrap().value(), &0);
}
}
```
=> Fix overflowing shift right with Default setting ncb to zero.

src/iter.rs, src/lib.rs, src/mapref/one.rs
I removed some unnecessary PhanomDatas and some unnecessary creations of Vecs. I also replaced `(shard_amount as f32).log2() as usize` with `shard_amount.trailing_zeros() as usize`, which is probably much faster because it assumes that `shard_amount` is always a power of two, which it is.
=> Some minor improvements.

Cargo.toml, src/iter.rs, src/lib.rs, src/mapref/entry.rs, src/mapref/multiple.rs, src/mapref/one.rs, src/t.rs, src/util.rs
Basically the only changes were changing imports from `std` to `core` and adding the dependency `hashbrown` for the `no_std` feature. `hashbrown` is used only to replace std's `HashMap`, everything else is the same code, and should in reality deviate even less from std than it would seem, as std itself depends on hashbrown for the things we depend on (`std::collections::hash_map` is a thin wrapper over `hashbrown::hash_map`, which this PR imports directly)
Adding no_std support was a breeze, apart from one hitch, `AbortOnPanic`. I left a comment there, but I'll just paste it here for convenience:
This is hard, as core/no_std has no concept of threads or knowledge of panicking.
An alternative would be to do this:
```rust
// Elsewhere in the library/host binary
use …
```
=> Added no_std support

src/lib.rs
Added the `DashMap::hasher` method to allow users to obtain a reference to the internal hasher of the current map, giving more parity with std's `HashMap`. Based off of the [`HashMap::hasher`] method
[`HashMap::hasher`]: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.hasher
=> Added the `DashMap::hasher` method

src/lib.rs
This could be changed to apply the first branch of the if statement (with slight modification) to all `with_capacity` calls that don't perfectly spread across shards to allow for exactly correct `with_capacity` calls
=> Added more correct capacity allocation

src/iter_set.rs, src/lib.rs, src/serde.rs, src/set.rs, src/setref/mod.rs, src/setref/multiple.rs, src/setref/one.rs
This is not yet complete, but should have all functionality working. Mostly it is just documentation that is missing.
Would close #34
I figure you can review what is here until I work on docs (will probably get to it in the next few days).
The Std HashSet implements `remove` as returning a bool and has a separate `take` that returns the item. I implemented `remove` so that it returns the item as I felt this was similar to DashMap's remove (which differs from std by returning `(K, V)` instead of just `V`). I can change this if you think it should be the same API as std.
Also, I'm not sure if things should be moved around. I tried to basically mirror the way DashMap is organized by creating a `mod setref` and `mod iter_set` though I could move things around if needed (I think it might be …
=> Add DashSet

Cargo.toml, src/lib.rs, src/mapref/entry.rs
Before this change one needed to clone() key before uses of entry
api that might return OccupiedEntry. Now you can do .into_key() and
use the key again for something else.
The enabler for this was that OccupiedEntry's key was an Option<K>,
but was always used as Some(). Fixing this to be K made into_key()
pretty simple to add.
Tested with cargo test
=> Add into_key() to Entry (was only on VacantEntry)

Cargo.toml, src/lib.rs, src/rayon/map.rs, src/rayon/set.rs, src/set.rs
This adds optional `rayon` trait implementations for collecting and
iterating `DashMap` and `DashSet` in parallel.
=> Add optional rayon support

src/iter.rs
Unsure if `V` should implement `Hash` and `Eq` as well, review needed for this.
This is being done so `serenity::cache::MessageIterator` can keep the Clone implement with the new DashMap cache rewrite that I'm working on.
modified:   src/iter.rs
=> Implement Clone to Iter

src/lib.rs, src/t.rs
Greetings!
Maybe I want to do something stupid, but here I come. I'm writing some subscribe / unsubscribe code and storing subscribers into HashMap with counter. When someone unsubscribes I'm decreasing counter and if counter reach zero entry is removing.
With RwLock it looks like this:
```rust
use std::{collections::HashMap, sync::RwLock};
struct Value {
counter: usize,
}
fn main() {
let map = RwLock::new(HashMap::from([("0".to_owned(), Value { counter: 1 })]));
{
let mut map = map.write().unwrap();
if let Some(Value { counter }) = map.get_mut("0") {
*counter -= 1;
if *counter == 0 {
println!("last");
map.remove("0");
}
}
}
println!("END");
}
```
Obvious with a lot of parallels sub / unsub events lock will be a bottleneck.
I can use `remove_if`, but because of deadlock I must drop …
=> Add remove_if_mut for Map.

src/lib.rs, src/serde.rs, src/set.rs
We are using DashMap `v3` and would like to migrate to `v4`. However, `v4` uses `std::collections::hash_map::RandomState`, which is slower than one `v3` uses (`ahash::RandomState`). When I parametrize DashMap with custom hasher, `serde` and `core::iter::FromIterator` don't work anymore.
This PR is attempt to fix this (it just implements these over generic DashMap).
resolves #130
=> support Serde and FromIterator for custom hashers

Cargo.toml, src/lib.rs
This PR adds support for setting a shard amount when initializing a `DashMap`. If not specified, the default shard amount calculated by CPU cores will be used.
=> Add support for setting shard amount.

Cargo.toml, src/iter.rs, src/lib.rs, src/read_only.rs
Two commits:
* switch to hashbrown
* use hashbrown `raw_entry` API to avoid hashing keys twice
Hashing twice issue can be solved by storing `(K, hash)` instead `K` in inner hashmap and supplying custom hash function.
With hashbrown raw entry API it is also possible to implement `Equivalent` API https://github.com/xacrimon/dashmap/issues/183.
The downside of this diff is that `shards` function now exposes hashbrown maps instead of std maps (switching to `(K, hash)` has the same issue) .
The alternative to this diff is to wait for stabilization of https://github.com/rust-lang/rust/issues/56167, as pointed in https://github.com/xacrimon/dashmap/issues/183.
=> Hash keys once

src/mapref/entry.rs
`Entry<K, V, S>` can be used without specifying type of `S`, as
`Entry<K, V>`.
Do the same for `VacantEntry` and `OccupiedEntry`.
=> VacantEntry/OccupiedEntry default type for S

Cargo.toml
Removes the transient dependency on `ahash`.
=> Tune hashbrown feature set

Cargo.toml
This crate uses available_parallelism which was introduced in Rust 1.59.
`rust-version` is a field for indicating MSRV: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
=> Set rust-version to 1.59

src/lib.rs
Closes https://github.com/xacrimon/dashmap/issues/170.
Add `DashMap::try_reserve` method that tries to allocate additional space in each of the shards, erring if any of the shards underlying `hashbrown::HashMap::try_reserve` calls errors.
=> feat: add try_reserve method

Cargo.toml, src/lib.rs
Closes https://github.com/xacrimon/dashmap/issues/219.
Use `once_cell` crate to memoize the value.
This doesn't add any new dependencies, as `once_cell` was already a subdependency. Additionally, it was merged into std in nightly and is awaiting stabilization.
=> feat: memoize default shard amount

src/lib.rs, src/rayon/map.rs, src/rayon/read_only.rs, src/read_only.rs
Closes https://github.com/xacrimon/dashmap/issues/136.
=> feat: add ReadOnlyView::par_iter() and ReadOnlyView::into_par_iter()

src/lib.rs, src/read_only.rs
These methods are natural extensions to the `raw-api` feature.
I'm using these methods in my attempts at making [Ascent](https://github.com/s-arash/ascent) parallel.
=> Add `shards_mut()` and `into_shards()` to `DashMap` and `shards()` to `ReadOnlyView`

src/serde.rs
This PR implements `serde::Serialize` for all reference types that implement `Deref<Target = impl Serialize>` if the `serde` feature is enabled.
This is useful if you have a library that takes an `impl Serialize` and you only have a reference to a `Dashmap` entry.
=> Implement `Serialize` for reference types

src/mapref/entry.rs
1. Added `VacantEntry::insert_entry` [as in the std](https://doc.rust-lang.org/std/collections/hash_map/struct.VacantEntry.html#method.insert_entry).
2. Added `Entry::insert_entry` [as in the std](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.insert_entry).
Unfortunately I was not able to achieve this without requiring the key `K` to be `Clone`, but I think it's better than nothing.
For cases where the key is not `Clone` or shouldn't be cloned, I ...
3. ... added `Entry::insert`, which makes sense to me, but is not a function in the std.
=> Entry insert

src/lib.rs, src/read_only.rs
Only hash keys once, by taking advantage of hashbrown raw entry api. This is roughly the same as #194.
=> Only hash keys once

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/rayon/map.rs, src/read_only.rs, src/set.rs
Using CachePadded to cache-align the rwlock shards for improved locking performance. This offers _considerable_ (30-50%) improvements in both latency and throughput perf on my M2.
> [!NOTE]  
> This increases memory usage. On x86_64, the cache alignment is set to 128. The current size of `RwLock<HashMap<K, V, std::RandomState>>` is `8 + 16 + 32 = 56` bytes. The current size of `RwLock<HashMap<K, V, ahash::RandomState>>` is `8 + 32 + 32 = 72` bytes. So this will double the size of the **empty** collection. Eg on a 64 core CPU the empty std dashmap size will increase from 14KiB to 32KiB. This size increase is constant though and does not scale per element inserted into the map.
> [!IMPORTANT]  
> This is a breaking change for the raw shards api.
<details>
<summary>Benchmark …
=> cache-align the shards to improve throughput

src/lib.rs
This makes it easy to `use dashmap::{DashMap, Entry}` rather than
requiring `dashmap::mapref::entry::Entry`.
This also makes it convenient to use `dashmap::Entry` as a qualified
type, in code that has other types named `Entry`.
=> Re-export Entry types at top level

src/util.rs
- Forget the abort on panic once we know the closure did not panic.
=> Allow map_in_place to be called when the callee is already panicking.

Cargo.lock, Cargo.toml, src/iter.rs, src/iter_set.rs, src/lib.rs, src/mapref/entry.rs, src/mapref/multiple.rs, src/mapref/one.rs, src/rayon/map.rs, src/rayon/read_only.rs, src/rayon/set.rs, src/read_only.rs, src/serde.rs, src/set.rs, src/setref/multiple.rs, src/setref/one.rs, src/t.rs, src/util.rs
Replace internal hashtable with hashbrown RawTable.
Benefits
* Allows only hashing keys once
* Allows a more efficient implementation of the Entry api. Which will always be a single hashtable operation.
* Previously, building the entry would lookup the hashtable once, and other operations would do another lookup (e.g. OccupiedEntry::remove or VacantEntry::insert).
* Allows dashmap raw api to be safely exposed even with the improvements above, as the shards are raw tables w/o hashers. This will avoid problems like https://github.com/xacrimon/dashmap/pull/259. crates.io use case (iterate the removed shards) will still be possible with rawtables.
* Removes a lot of generic types for the hasher
* Slightly simplifies some code paths as we don't have to fight lifetimes
The first two can be …
=> Replace internal hashtable with hashbrown RawTable

Cargo.lock, Cargo.toml, src/lib.rs, src/set.rs
This allows using typesize with dashmap without me having to maintain the code in typesize, which leads to a bunch of problems including privacy issues. Those safety comments definitely need a double check as I'm not too sure what magic is being done with RawTable.
=> Add typesize::TypeSize implementation for DashMap/DashSet

src/iter.rs, src/lib.rs, src/mapref/entry.rs, src/rayon/map.rs, src/read_only.rs, src/util.rs
This is a breaking change to the raw-api feature.
I looked at the history of SharedValue. It was introduced to fix #10 to circumvent some pointer shenanigans. 
I looked through the code and couldn't find anything relevant anymore. All pointers in a RefMut are derived from `&mut V` and never convert through `&V`, thus we never have a case where `&V -> &mut V`.
I have tested with miri too, which would definitely complain if this is violated.
(this is a pre-requisite for some later changes I wish to make, see #314)
=> remove SharedValue

src/iter.rs, src/iter_set.rs, src/lib.rs, src/lock.rs, src/mapref/entry.rs, src/mapref/multiple.rs, src/mapref/one.rs, src/rayon/map.rs, src/read_only.rs, src/serde.rs, src/util.rs
(stacked on top of #322)
I came up with this novel abstraction for reducing the dependencies on pointers within dashmap. We need to hold the lock guard for the shard.
Since Ref/Mut wants to get proper reference values eventually, it doesn't matter whether you convert pointers early or later. It seems to work all the same. 
Thus, we can convert 
```rust
pub struct Ref<'a, K, V> {
_guard: RwLockReadGuard<'a, HashMap<K, V>>,
k: *const K,
v: *const V,
}
```
into
```rust
pub struct Ref<'a, K, V> {
_guard: RwLockReadGuardDetached<'a>,
k: &'a K,
v: &'a V,
}
```
Since the detached guard does not own the data, it's inherently unsafe, but from my understanding and from asking others, it is still sound as long as the data is still coupled with the guard. `Ref`/`Entry` APIs still hold the guard, …
=> Remove large amounts of unsafe from Refs via 'detached' lock guards

Cargo.lock, Cargo.toml, src/iter.rs, src/iter_set.rs, src/lib.rs, src/lock.rs, src/mapref/entry.rs, src/mapref/multiple.rs, src/mapref/one.rs, src/rayon/map.rs, src/read_only.rs, src/serde.rs, src/util.rs
(this PR is stacked on top of #323)
Upgrades hashbrown 0.14 to hashbrown 0.15. Major difference is that RawTable is no longer available, so we must use HashTable instead. Because of my prior two PRs, this change ends up being pretty light and fortunately removes some more unsafe
This is a breaking change to the raw-api feature.
=> hashbrown 0.15

src/lib.rs
The dashmap page on docs.rs looked a little bit empty. This should fix it.
=> Set readme contents as crate docs

src/mapref/one.rs, src/util.rs
Fixes #328 
When fixing, I made sure the "Detached" impls all matched lock-api's native lock types. In the process, I spotted that our MappedRef types don't use `?Sized` bounds, so I introduced this and added some tests there too.
=> fix downgrade

src/lib.rs, src/mapref/entry.rs, src/mapref/entry_ref.rs, src/mapref/mod.rs
As discussed in https://github.com/xacrimon/dashmap/issues/183
Adds an EntryRef API similar to https://docs.rs/hashbrown/latest/hashbrown/hash_map/enum.EntryRef.html
The main difference is that I also added an OccupiedEntryRef type which can return the borrowed `&Q` key in the `key()` function and it means that `VacantEntryRef::insert_entry` doesn't have to convert from `&Q` to `K` twice
BTW, nice job moving to the detached guards, that made this very easy!
=> Add (try_)entry_ref functions and EntryRef types
